from typing import Dict, Any, List
from PIL import Image
import random
from .base import BaseVLM

class DemoVLM(BaseVLM):
    """
    Demo VLM that provides realistic-looking responses without requiring GPU or large models.
    This allows the application to be demonstrated on any hardware.
    """
    
    def __init__(self, model_name: str = "demo-vlm", device: str = "cpu"):
        super().__init__(model_name, device)
        
        self.change_responses = [
            "Analysis detected significant changes in the northeastern region of the image. "
            "New built-up structures are visible, with approximately 15-20 new buildings identified. "
            "Vegetation coverage has decreased by an estimated 12% in the central area. "
            "Road infrastructure shows expansion, particularly along the eastern boundary.",
            
            "Temporal analysis reveals substantial urban development between the two time periods. "
            "The system identified new construction activity covering approximately 3.2 hectares. "
            "Agricultural land conversion to residential areas is evident in the southern section. "
            "Water body extent has reduced by approximately 8%.",
            
            "Change detection algorithm identified modifications across 18% of the total area. "
            "Primary changes include: new infrastructure development, vegetation loss in northern zones, "
            "and apparent land use transformation from agricultural to urban classification.",
        ]
        
        self.object_detection_responses = [
            "Object detection analysis identified multiple features of interest. "
            "Detected: 47 buildings, 12 road segments, 3 water bodies, and 8 agricultural structures. "
            "The majority of buildings are concentrated in the central and eastern regions. "
            "Road network shows a well-developed grid pattern.",
            
            "The system successfully detected various infrastructure elements. "
            "Buildings: 32 residential structures, 5 commercial buildings. "
            "Transportation: 15 road segments, 2 parking areas. "
            "Natural features: 4 vegetation clusters, 2 water bodies.",
            
            "Analysis completed with detection of key objects: "
            "Urban infrastructure (38 buildings), transportation network (18 road segments), "
            "and environmental features (6 vegetation areas, 1 river/stream).",
        ]
        
        self.general_responses = [
            "The satellite imagery shows a mixed-use area with both urban and rural characteristics. "
            "Vegetation is present primarily in the northern and western sections. "
            "Built-up areas are concentrated in the eastern region. "
            "The image appears to be captured during clear weather conditions with good visibility.",
            
            "Analysis indicates a transitional zone between urban and agricultural land use. "
            "Infrastructure development is evident with roads and buildings visible. "
            "Natural features including vegetation and possible water bodies are present. "
            "The image quality is suitable for detailed remote sensing analysis.",
            
            "The imagery reveals a landscape with diverse land cover types. "
            "Human settlement patterns are visible alongside natural and agricultural areas. "
            "The spatial resolution allows for identification of individual structures and features.",
        ]
    
    def load_model(self):
        """No model loading required for demo mode."""
        print("[DEMO MODE] VLM model loaded (simulation)")
    
    def analyze(self, image: Image.Image, query: str, **kwargs) -> Dict[str, Any]:
        """Provide demo analysis response."""
        query_lower = query.lower()
        
        # Determine response type based on query
        if any(word in query_lower for word in ["change", "compare", "difference", "temporal"]):
            answer = random.choice(self.change_responses)
        elif any(word in query_lower for word in ["detect", "identify", "find", "building", "road"]):
            answer = random.choice(self.object_detection_responses)
        else:
            answer = random.choice(self.general_responses)
        
        # Generate demo confidence
        confidence = random.uniform(0.75, 0.92)
        
        return {
            "answer": answer,
            "confidence": round(confidence, 2),
            "model_used": "demo-vlm",
            "explanation": "This is a demonstration response. In production mode, this would be generated by the actual VLM model.",
            "demo_mode": True
        }
    
    def analyze_multi_image(
        self,
        images: List[Image.Image],
        query: str,
        **kwargs
    ) -> Dict[str, Any]:
        """Provide demo multi-image analysis."""
        # For multi-image, bias toward change detection responses
        answer = random.choice(self.change_responses)
        confidence = random.uniform(0.78, 0.90)
        
        return {
            "answer": answer,
            "confidence": round(confidence, 2),
            "model_used": "demo-vlm",
            "explanation": "Multi-temporal analysis in demonstration mode. Production version would use actual VLM with temporal reasoning capabilities.",
            "demo_mode": True,
            "num_images_analyzed": len(images)
        }